version: "3"
services:
  app:
    build:
      context: .
    env_file: ./.env
    image: node:14-slim
    command: sh -c "npm install && npm run start"
    ports:
      - $NODE_LOCAL_PORT:3000
    working_dir: /usr/src/app
    depends_on:
      - mongo
    environment:
      MONGO_HOST: mongo
      MONGO_URI: $MONGO_DOCKER_URI
    volumes:
      - ./:/usr/src/app
  mongo:
    image: mongo
    env_file: ./.env
    volumes:
      - ./data:/data/db
    environment:
      - PUID=1000
      - PGID=1000
    ports:
      - $MONGO_LOCAL_PORT:27017
